stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

test:
  image: cypress/browsers:22.15.0
  stage: test
  script:
    # install dependencies
    - npm ci
    # run Cypress tests
    - npx cypress run --browser chrome
  artifacts:
    when: always
    paths:
      - cypress/reports
      - cypress/screenshots/**/*.png
    expire_in: 1 day